language: node_js
node_js:
  - "node"
cache:
  directories:
    - ./react-frontend/node_modules
script:
  - cd react-frontend
  - yarn install
  - yarn build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
