exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("flights")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("flights").insert([
        {
          id: 1,
          flightDate: "10/12/2018",
          flightName: "national",
          airports: "Quinua",
          remarks: "Stand-alone background product",
          total: 4.0,
          numOfTakeOffs: 2,
          numOfLandings: 2,
          SEL: 0.6,
          MEL: 0,
          dayHours: 3.0,
          nightHours: 1.4,
          actInstruments: 4.0,
          simInstruments: 4.1,
          groundTrainer: 0,
          crossCountry: 1.7,
          asInstructor: 0,
          dualReceived: 0,
          pilotInCommand: 0.6,
          airPlanesID: 1,
          pilotsUID: "583-78-0825"
        },
        {
          id: 2,
          flightDate: "6/22/2018",
          flightName: "encryption",
          airports: "Vale Flores",
          remarks: "Upgradable intangible policy",
          total: 0.9,
          numOfTakeOffs: 2,
          numOfLandings: 1,
          SEL: 4.8,
          MEL: 0,
          dayHours: 0.8,
          nightHours: 1.0,
          actInstruments: 4.8,
          simInstruments: 2.9,
          groundTrainer: 0,
          crossCountry: 2.7,
          asInstructor: 0,
          dualReceived: 0,
          pilotInCommand: 3.1,
          airPlanesID: 1,
          pilotsUID: "583-78-0825"
        },
        {
          id: 3,
          flightDate: "9/14/2018",
          flightName: "internet solution",
          airports: "Guiniculalay",
          remarks: "Intuitive executive capability",
          total: 0.1,
          numOfTakeOffs: 0,
          numOfLandings: 0,
          SEL: 2.7,
          MEL: 0,
          dayHours: 3.4,
          nightHours: 1.5,
          actInstruments: 4.6,
          simInstruments: 2.2,
          groundTrainer: 0,
          crossCountry: 2.8,
          asInstructor: 0,
          dualReceived: 0,
          pilotInCommand: 2.7,
          airPlanesID: 1,
          pilotsUID: "583-78-0825"
        },
        {
          id: 4,
          flightDate: "7/12/2018",
          flightName: "collaboration",
          airports: "Almafuerte",
          remarks: "Streamlined secondary encryption",
          total: 0.8,
          numOfTakeOffs: 1,
          numOfLandings: 1,
          SEL: 4.2,
          MEL: 0,
          dayHours: 4.5,
          nightHours: 3.8,
          actInstruments: 3.9,
          simInstruments: 3.3,
          groundTrainer: 0,
          crossCountry: 4.7,
          asInstructor: 0,
          dualReceived: 0,
          pilotInCommand: 2.7,
          airPlanesID: 1,
          pilotsUID: "583-78-0825"
        },
        {
          id: 5,
          flightDate: "10/24/2018",
          flightName: "homogeneous",
          airports: "Witzenhausen",
          remarks: "Diverse explicit moratorium",
          total: 0.2,
          numOfTakeOffs: 1,
          numOfLandings: 1,
          SEL: 2.0,
          MEL: 0,
          dayHours: 3.8,
          nightHours: 3.3,
          actInstruments: 0.6,
          simInstruments: 4.8,
          groundTrainer: 0,
          crossCountry: 2.3,
          asInstructor: 0,
          dualReceived: 0,
          pilotInCommand: 0.2,
          airPlanesID: 1,
          pilotsUID: "583-78-0825"
        },
        {
          id: 6,
          flightDate: "5/5/2018",
          flightName: "utilisation",
          airports: "Skarbimierz Osiedle",
          remarks: "Synergistic directional core",
          total: 0.4,
          numOfTakeOffs: 1,
          numOfLandings: 0,
          SEL: 1.6,
          MEL: 0,
          dayHours: 3.3,
          nightHours: 4.9,
          actInstruments: 4.9,
          simInstruments: 0.1,
          groundTrainer: 0,
          crossCountry: 0.6,
          asInstructor: 0,
          dualReceived: 0,
          pilotInCommand: 4.8,
          airPlanesID: 1,
          pilotsUID: "583-78-0825"
        },
        {
          id: 7,
          flightDate: "11/29/2018",
          flightName: "Grass-roots",
          airports: "Burqah",
          remarks: "Cloned tertiary structure",
          total: 1.7,
          numOfTakeOffs: 2,
          numOfLandings: 1,
          SEL: 3.1,
          MEL: 0,
          dayHours: 4.3,
          nightHours: 2.6,
          actInstruments: 2.5,
          simInstruments: 2.9,
          groundTrainer: 0,
          crossCountry: 4.6,
          asInstructor: 0,
          dualReceived: 0,
          pilotInCommand: 1.4,
          airPlanesID: 1,
          pilotsUID: "583-78-0825"
        },
        {
          id: 8,
          flightDate: "6/2/2018",
          flightName: "circuit",
          airports: "Cincinnati",
          remarks: "Re-contextualized zero administration implementation",
          total: 2.4,
          numOfTakeOffs: 2,
          numOfLandings: 2,
          SEL: 0.2,
          MEL: 0,
          dayHours: 1.7,
          nightHours: 3.0,
          actInstruments: 1.5,
          simInstruments: 2.5,
          groundTrainer: 0,
          crossCountry: 2.7,
          asInstructor: 0,
          dualReceived: 0,
          pilotInCommand: 3.0,
          airPlanesID: 1,
          pilotsUID: "583-78-0825"
        },
        {
          id: 9,
          flightDate: "2/3/2018",
          flightName: "Versatile",
          airports: "Mahābād",
          remarks: "Sharable 3rd generation open system",
          total: 4.8,
          numOfTakeOffs: 1,
          numOfLandings: 1,
          SEL: 3.9,
          MEL: 0,
          dayHours: 4.9,
          nightHours: 1.0,
          actInstruments: 1.6,
          simInstruments: 1.5,
          groundTrainer: 0,
          crossCountry: 1.1,
          asInstructor: 0,
          dualReceived: 0,
          pilotInCommand: 2.7,
          airPlanesID: 1,
          pilotsUID: "583-78-0825"
        },
        {
          id: 10,
          flightDate: "10/1/2018",
          flightName: "exuding",
          airports: "Qujiang",
          remarks: "Realigned user-facing strategy",
          total: 2.4,
          numOfTakeOffs: 1,
          numOfLandings: 1,
          SEL: 2.4,
          MEL: 0,
          dayHours: 1.7,
          nightHours: 1.6,
          actInstruments: 3.0,
          simInstruments: 4.3,
          groundTrainer: 0,
          crossCountry: 1.2,
          asInstructor: 0,
          dualReceived: 0,
          pilotInCommand: 2.8,
          airPlanesID: 1,
          pilotsUID: "583-78-0825"
        }
      ]);
    });
};
